export const postsActionsTypes = {
  GET_POSTS_START: 'GET_POSTS_START',
  GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
  GET_POSTS_FAILURE: 'GET_POSTS_FAILURE',
  SHOW_NEXT_PAGE: 'SHOW_NEXT_PAGE',
  SHOW_PREVIOS_PAGE: 'SHOW_PREVIOS_PAGE',
};

export default postsActionsTypes;
