export const postsActionsTypes = {
  GET_POSTS_START: 'GET_POSTS_START',
  GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
  GET_POSTS_FAILURE: 'GET_POSTS_FAILURE',
  SHOW_NEXT_PAGE: 'SHOW_NEXT_PAGE',
  SHOW_PREVIOS_PAGE: 'SHOW_PREVIOS_PAGE',
  GET_COMMENTS_START: 'GET_COMMETNS_START',
  GET_COMMENTS_SUCCESS: 'GET_COMMETNS_SUCCESS',
  GET_COMMENTS_FAILURE: 'GET_COMMETNS_FAILURE',
  CREATE_COMMENT_START: 'CREATE_COMMENT_START',
  CREATE_COMMENT_SUCCESS: 'CREATE_COMMENT_SUCCESS',
  CREATE_COMMENT_FAILURE: 'CREATE_COMMENT_FAILURE',
};

export default postsActionsTypes;
