export const allUsersActionTypes = {
  GET_USERS_START: 'GET_USERS_START',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_FAILURE: 'GET_USERS_FAILURE',
  CHANGE_USER_PROFILE_START: 'CHANGE_USER_PROFILE_START',
  CHANGE_USER_PROFILE_SUCCESS: 'CHANGE_USER_PROFILE_SUCCESS',
  CHANGE_USER_PROFILE_FAILURE: 'CHANGE_USER_PROFILE_FAILURE',
  TOGGLE_SEARCHING_FIELD: 'TOGGLE_SEARCHING_FIELD',
  CLOSE_SEARCHING_FIELD: 'CLOSE_SEARCHING_FIELD',
  CREATE_USER_START: 'CREATE_USER_START',
  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER_FAILURE: 'CREATE_USER_FAILURE',
  CHECK_USER_AUTH: 'CHECK_USER_AUTH',
  LOGIN_USER_START: 'LOGIN_USER_START',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
  LOGOUT_USER_START: 'LOGOUT_USER_START',
  LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS',
  LOGOUT_USER_FAILURE: 'LOGOUT_USER_FAILURE',
};

export default allUsersActionTypes;
